Project_MVC/Controllers/ShoppingCartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Project_MVC.Data;
using Project_MVC.Models;

namespace Project_MVC.Controllers
{
    public class ShoppingCartsController : Controller
    {
        private readonly ApplicationDbContext _context;
       
        public ShoppingCartsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ShoppingCarts
        [Authorize(Roles = "User , Admin")]
        public async Task<IActionResult> Index()
        {
            List<JoinedShoppingCart> joinedShoppingCart = new();
            joinedShoppingCart = await (from s in _context.ShoppingCarts
                        join p in _context.Products
                        on s.ProductId equals p.ProductId
                        select new JoinedShoppingCart
                        {
                            Id = s.Id,
                            ProductId = s.ProductId,
                            Nazwa = p.Name,
                            Ilosc = s.Ilosc,
                            Cena = p.Price
                        }).ToListAsync();
            ViewBag.Total = joinedShoppingCart.Sum(x=> x.Ilosc * x.Cena);
            return View(joinedShoppingCart);
        }

   
        // GET: ShoppingCarts/Details/5
        [Authorize(Roles = "User , Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ShoppingCarts == null)
            {
                return NotFound();
            }

            var shoppingCart = await _context.ShoppingCarts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shoppingCart == null)
            {
                return NotFound();
            }

            return View(shoppingCart);
        }

    
        public IActionResult plus(int id)
        {
            var cartItem = _context.ShoppingCarts.FirstOrDefault(m => m.Id == id);
            if (cartItem.Ilosc == 1)
            {
                cartItem.Ilosc++;
            }
            _context.SaveChanges();
            return RedirectToAction("Index");

        }

        public IActionResult minus (int id)
        {
            var cartItem = _context.ShoppingCarts.FirstOrDefault(m => m.Id == id);
            if (cartItem.Ilosc >1)
            {
                cartItem.Ilosc--;
            }
            _context.SaveChanges();
            return RedirectToAction("Index");

        }
        /*// GET: ShoppingCarts/Create
        [Authorize(Roles = "User , Admin")]
        public IActionResult Create()
        {
            return View();
        }*/

        /*// POST: ShoppingCarts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User , Admin")]
        public async Task<IActionResult> Create([Bind("Id,ProductId,UserId,Ilosc")] ShoppingCart shoppingCart)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shoppingCart);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(shoppingCart);
        }*/

        // GET: ShoppingCarts/Edit/5
        [Authorize(Roles = "User , Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ShoppingCarts == null)
            {
                return NotFound();
            }

            var shoppingCart = await _context.ShoppingCarts.FindAsync(id);
            if (shoppingCart == null)
            {
                return NotFound();
            }
            return View(shoppingCart);
        }

        // POST: ShoppingCarts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User , Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProductId,UserId,Ilosc")] ShoppingCart shoppingCart)
        {
            if (id != shoppingCart.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shoppingCart);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShoppingCartExists(shoppingCart.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(shoppingCart);
        }

        // GET: ShoppingCarts/Delete/5
        [Authorize(Roles = "User , Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ShoppingCarts == null)
            {
                return NotFound();
            }

            var shoppingCart = await _context.ShoppingCarts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shoppingCart == null)
            {
                return NotFound();
            }

            return View(shoppingCart);
        }

        public async Task<ActionResult> Payment()
        {
            var name = User.Identity.Name;

            //var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());

                var order = new Order
                {
                    //FirstName = user.Imie,
                    //LastName = user.Nazwisko,
                   // Address = user.Adres,
                   // City = user.Miasto,
                   // PostCode = user.KodPocztowy,
                   // Email = user.Email,
                    //TelephoneNumber = user.Telefon
                };
                return View(order);
        }
        [HttpPost]
        public async Task<ActionResult> Pay(Order order, int id)
        {
            if (ModelState.IsValid)
            {

                var userId = User.Identity.GetUserId();

                // utworzyć obiekt zamowienia na podstawie tego co mamy w koszyku
               // var newOrder = ;

                // aktualizacja danych użytkownika
               // var user = await _context.Users.FindAsync(userId);
               /// TryUpdateModel(user.);
               // await UserManager.UpdateAsync(user);

       
                var shoppingCart = await _context.ShoppingCarts.FindAsync(id);
                if (shoppingCart != null)
                {
                    _context.ShoppingCarts.Remove(shoppingCart);
                }


                return RedirectToAction("PotwierdzenieZamowienia");
            }
            else
                return View();
        }


        public ActionResult OrderConfirmation()
        {
            return View(); 
        }

       




        // POST: ShoppingCarts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User , Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ShoppingCarts == null)
            {
                return Problem("Entity set 'ApplicationDbContext.ShoppingCarts'  is null.");
            }
            var shoppingCart = await _context.ShoppingCarts.FindAsync(id);
            if (shoppingCart != null)
            {
                _context.ShoppingCarts.Remove(shoppingCart);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShoppingCartExists(int id)
        {
          return _context.ShoppingCarts.Any(e => e.Id == id);
        }
    }
}

Project_MVC/Views/Shared/_AdminPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        @if (ViewContext.HttpContext.User.IsInRole("Admin"))
        {
            <li class="nav-item">
                <a href="/Admin" class="nav-link text-dark">Panel administratora</a>
            </li>
        }
    }
</ul>

Project_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShopApp</title>
    <link rel="stylesheet" href="~/css/Minty.css" />
</head>
    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DietApp</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Produkty</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Zamówiena</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Category" asp-action="Index">Kategorie</a>
                        </li>
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ShoppingCarts" asp-action="Index">Koszyk</a>
                        </li>
                        </ul>
                        <partial name="_AdminPartial" />
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2022 - ShopApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>